### ISSUE TITLE
I really like to have a "random" Link-Lokal-Address

### ISSUE THREAD

**Issue by genofire** [christf/wg-broker#10]
https://github.com/christf/wg-broker/blob/654893248fe32c89bddeb1e2b61a619de733a82e/src/wg-broker-server#L89

**Comment by christf** [comment]
Since this issue was raised this is implemented. Thank you for your input!

**Comment by genofire** [comment]
This is not random - it is psydo-ramdom.

So if you have multiple wg-broker on the network you would have same Link-Local-Address if you list all lladdr in the babel-network.

(Yes this make no problem in network, just with respondd - because it is not possible find the correct mapping of neighbours to get the bidirectional link )

**Comment by christf** [comment]
On Tue, Nov 26, 2019 at 01:27:59AM -0800, genofire wrote:
>This is not random - it is psydo-ramdom.
>
>So if you have multiple wg-broker on the network you would have same 
>Link-Local-Address if you list all lladdr in the babel-network.
>
>(Yes this make no problem in network, just with respondd - because it 
>is not possible find the correct mapping of neighbours to get the 
>bidirectional link )
Even randomness does not avoid the problem. You can still have 
collisions.

-- 
()  ascii ribbon campaign - against html e-mail
/\  www.asciiribbon.org   - against proprietary attachments

**Comment by genofire** [comment]
usually link local address is generated from mac-address which should be unique ;(

maybe something from `/etc/machine-id`
```sh
  ip a a fe80::$(sed 's/\([0-9a-f]\{4\}\)\([0-9a-f]\{4\}\)\([0-9a-f]\{4\}\).*/\1:\2:\3/' /etc/machine-id):$devicenumber/64 dev $newdevice
```
